FROM maven:3.9.8-amazoncorretto-21 AS build

WORKDIR /app

# Copy root pom.xml
COPY . .

RUN mvn package -pl processes/payment -am -DskipTests

FROM amazoncorretto:21-alpine

EXPOSE 8092

RUN mkdir /app

COPY --from=build /app/processes/payment/target/*.jar /app/spring-boot-application.jar

CMD ["java","-jar","/app/spring-boot-application.jar"]
