FROM maven:3.9.8-amazoncorretto-21 AS build

WORKDIR /app

# Copy the parent pom.xml
COPY . .

RUN mvn package -pl taskmanager -am -DskipTests

FROM amazoncorretto:21-alpine

EXPOSE 8090

RUN mkdir /app

COPY --from=build /app/taskmanager/target/*.jar /app/spring-boot-application.jar

CMD ["java","-jar","/app/spring-boot-application.jar"]
