FROM maven:3.9.8-amazoncorretto-21 AS build

WORKDIR /app

# Copy everything defined by the .dockerignore file
COPY . .

RUN mvn package -pl processes/order -am -DskipTests

FROM amazoncorretto:21-alpine

EXPOSE 8091

RUN mkdir /app

COPY --from=build /app/processes/order/target/*.jar /app/spring-boot-application.jar

CMD ["java","-jar","/app/spring-boot-application.jar"]
