server:
  port: 9100

spring:
  application:
    name: taskmanager
  flyway:
    locations: classpath:db/migration
    schemas: task_schema
    baseline-on-migrate: true
    enabled: true
  datasource:
    driver-class-name: ${LOCAL_DATASOURCE_DRIVER}
    url: ${TM_JDBC_BASE_URL}?currentSchema=task_schema
    username: ${LOCAL_DATASOURCE_USER}
    password: ${LOCAL_DATASOURCE_PASSWORD}

camunda:
  client:
    zeebe:
      base-url: http://localhost:26500
    mode: simple
