server:
  port: 9100

management:
  endpoint:
    web:
      exposure:
        include: health,info

spring:
  application:
    name: taskmanager
  flyway:
    locations: classpath:db/migration
    schemas: task_schema
    baseline-on-migrate: true
    enabled: true
  datasource:
    driver-class-name: ${LOCAL_DATASOURCE_DRIVER:org.postgresql.Driver}
    url: ${JDBC_BASE_URL:jdbc:postgresql://localhost:5432/taskmanager}?currentSchema=task_schema
    username: ${LOCAL_DATASOURCE_USER:postgres}
    password: ${LOCAL_DATASOURCE_PASSWORD:postgres}

camunda:
  client:
    zeebe:
      gateway-url: ${ZEEBE_BASE_URL:http://localhost:26500}
    mode: simple

miranum.tm.process-application:
  order:
    base-url: ${ORDER_BASE_URL:http://localhost:9101}
    startable: true
  payment:
    base-url: ${PAYMENT_BASE_URL:http://localhost:9102}
    startable: true

