services:

  zeebe:
    image: camunda/zeebe:8.5.1
    container_name: zeebe
    ports:
      - "26500:26500"
      - "9600:9600"
    env_file:
      - zeebe.env
    environment:
      - "JAVA_TOOL_OPTIONS=-Xms512m -Xmx512m"
    restart: always
    #volumes:
    #  - .data/zeebe:/usr/local/zeebe/data
    networks:
      - internal
    depends_on:
      elasticsearch:
        condition: service_healthy

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    container_name: zeebe-elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - cluster.routing.allocation.disk.threshold_enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200/_cat/health | grep -q green" ]
      interval: 5s
      retries: 30
    networks:
      - internal

  postgres:
    image: postgres:15.3
    container_name: postgres
    volumes:
      - ./postgres/:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - common.env
    environment:
      - POSTGRES_MULTIPLE_DATABASES=${TM_DATASOURCE_DB},${ORDER_DATASOURCE_DB},${PAYMENT_DATASOURCE_DB}
    networks:
      - internal

  nginx:
    image: nginx:1.24.0
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    ports:
      - "8081:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      taskmanager:
        condition: service_healthy
      order-process:
        condition: service_healthy
      payment-process:
        condition: service_healthy
    profiles:
      - prod
    networks:
      - internal

  tasklist:
    container_name: tasklist
    build:
      context: ../apps/tasklist
      target: prod
      args:
        - VITE_BASE_URL=${PROCESS_BASE_URL}
    ports:
      - "3000:8080"
    restart: unless-stopped
    profiles:
      - prod
    networks:
      - internal

  taskmanager:
    container_name: taskmanager
    build:
      context: ../.
      dockerfile: taskmanager/Dockerfile
    ports:
      - "8090:${TM_PORT}"
    restart: unless-stopped
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:${TM_PORT}/actuator/health || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 5s
    env_file:
      - common.env
    environment:
      - TM_PORT=${TM_PORT}
      - TM_JDBC_URL=${TM_JDBC_URL}
      - ORDER_BASE_URL=${ORDER_BASE_URL}
      - PAYMENT_BASE_URL=${PAYMENT_BASE_URL}
    profiles:
      - prod
    depends_on:
      - zeebe
      - postgres
    networks:
      - internal

  order-process:
    container_name: order-process
    build:
      context: ../.
      dockerfile: processes/order/Dockerfile
    ports:
      - "8091:${ORDER_PORT}"
    restart: unless-stopped
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:${ORDER_PORT}/actuator/health || exit 1"
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 5s
    env_file:
      - common.env
    environment:
      - ORDER_PORT=${ORDER_PORT}
      - ORDER_JDBC_URL=${ORDER_JDBC_URL}
    profiles:
      - prod
    depends_on:
      - zeebe
      - postgres
    networks:
      - internal

  payment-process:
    container_name: payment-process
    build:
      context: ../.
      dockerfile: processes/payment/Dockerfile
    ports:
      - "8092:${PAYMENT_PORT}"
    restart: unless-stopped
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:${PAYMENT_PORT}/actuator/health || exit 1"
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 5s
    env_file:
      - common.env
    environment:
      - PAYMENT_PORT=${PAYMENT_PORT}
      - PAYMENT_JDBC_URL=${PAYMENT_JDBC_URL}
    profiles:
      - prod
    depends_on:
      - zeebe
      - postgres
    networks:
      - internal

networks:
  internal: