server:
  port: 9101

spring:
  application:
    name: payment-process
  flyway:
    locations: classpath:db/migration
    schemas: payment_schema
    baseline-on-migrate: true
    enabled: true
  datasource:
    driver-class-name: ${LOCAL_DATASOURCE_DRIVER}
    url: ${PYMT_JDBC_BASE_URL}?currentSchema=payment_schema
    username: ${LOCAL_DATASOURCE_USER}
    password: ${LOCAL_DATASOURCE_PASSWORD}

camunda:
  client:
    zeebe:
      base-url: http://localhost:26500
