server:
  port: 9102

payment:
  id: payment-process
  name: Payment Process
  startable: true

spring:
  application:
    name: payment-process
  flyway:
    locations: classpath:db/migration
    schemas: payment_schema
    baseline-on-migrate: true
    enabled: true
  datasource:
    driver-class-name: ${LOCAL_DATASOURCE_DRIVER:org.postgresql.Driver}
    url: ${JDBC_BASE_URL:jdbc:postgresql://localhost:5432/paymentprocess}?currentSchema=payment_schema
    username: ${LOCAL_DATASOURCE_USER:postgres}
    password: ${LOCAL_DATASOURCE_PASSWORD:postgres}

camunda:
  client:
    zeebe:
      gateway-url: ${ZEEBE_BASE_URL:http://localhost:26500}
    mode: simple
