server:
  port: 9101

order:
  id: order-process
  name: Order Process
  startable: true

management:
  endpoint:
    web:
      exposure:
        include: health,info

spring:
  application:
    name: order-process
  flyway:
    locations: classpath:db/migration
    schemas: order_schema
    baseline-on-migrate: true
    enabled: true
  datasource:
    driver-class-name: ${LOCAL_DATASOURCE_DRIVER:org.postgresql.Driver}
    url: ${JDBC_BASE_URL:jdbc:postgresql://localhost:5432/orderprocess}?currentSchema=order_schema
    username: ${LOCAL_DATASOURCE_USER:postgres}
    password: ${LOCAL_DATASOURCE_PASSWORD:postgres}

camunda:
  client:
    zeebe:
      gateway-url: ${ZEEBE_BASE_URL:http://localhost:26500}
    mode: simple
