### GET Tasks
GET http://localhost:8083/api/load/tasks
Accept: application/json

> {%
    client.global.set("task_id", response.body[1]["key"].toString());
%}

### PUT Start Process
PUT http://localhost:8081/api/process/start

### PUT Check Order Task
POST http://localhost:8081/api/task/complete/check/{{task_id}}

### PUT Prepare Order Task
POST http://localhost:8081/api/task/complete/prepare/{{task_id}}
