### POST Start Process
POST http://localhost:8091/rest/process/start
Content-Type: application/json

{
  "firstname": "John",
  "lastname": "Doe",
  "email": "john.doe@gmail.com",
  "street": "1234 Main St",
  "zip": "12345",
  "city": "Springfield",
  "items": [
    {
      "id": "123e4567-e89b-12d3-a456-426614174000",
      "quantity": 1
    }
  ]
}

### GET CheckOrder Task
GET http://localhost:9100/rest/tasks
Accept: application/json

> {%
    if (response.body.length > 0) {
        let res = response.body[0];
        res.assignee = "";
        client.global.set("user_task", JSON.stringify(res));
        client.global.set("element_id", res["elementId"]);
        console.log(client.global.get("user_task"));
    }
%}

### POST Load form for CheckOrderTask
POST http://localhost:8091/rest/task/load
Content-Type: application/json
Accept: application/json

{{user_task}}

### POST Complete CheckOrderTask
POST http://localhost:8091/rest/task/complete
Content-Type: application/json

{
  "userTask": {{user_task}},
  "formData": {
    "firstname": "John",
    "lastname": "Doe",
    "email": "john.doe@gmail.com",
    "street": "1234 Main St",
    "zip": "12345",
    "city": "Springfield",
    "items": [
      {
        "id": "123e4567-e89b-12d3-a456-426614174000",
        "name": "Item 1",
        "price": 10.99,
        "image": "https://via.placeholder.com/300",
        "quantity": 1
      }
    ],
    "isOrderValid": true
  }
}

### GET PrepareOrder Task
GET http://localhost:9100/rest/tasks
Accept: application/json

> {%
    if (response.body.length > 0) {
        let res = response.body[0];
        res.assignee = "";
        client.global.set("user_task", JSON.stringify(res));
        client.global.set("element_id", res["elementId"]);
        console.log(client.global.get("user_task"));
    }
%}

### POST Load form for PrepareOrderTask
POST http://localhost:8091/rest/task/load
Content-Type: application/json
Accept: application/json

{{user_task}}

### PUT Complete PrepareOrderTask
POST http://localhost:8091/rest/task/complete
Content-Type: application/json

{
  "userTask": {{user_task}},
  "formData": {
    "deliveryDate": "2021-12-31",
    "itemCheckList": [
      {
        "id": "123e4567-e89b-12d3-a456-426614174000",
        "name": "Item 1",
        "quantity": 1
      }
    ]
  }
}
